#!/bin/bash

CWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

mkdir -p ${CWD}/node_modules
if [ ! -L "${CWD}/node_modules/__buttercup" ]; then
	echo "Creating buttercup link..."
	cd ${CWD}/node_modules && ln -s ../source __buttercup && cd -
fi
