module.exports = {

	COMPONENTS_COUNT: 					4,
	DERIVED_KEY_ALGORITHM: 				"sha256",
	DERIVED_KEY_ITERATIONS: 			1000,
	ENC_ALGORITHM: 						"aes-256-cbc",
	HMAC_ALGORITHM: 					"sha256",
	HMAC_KEY_SIZE: 						32,
	PASSWORD_KEY_SIZE: 					32,
	SALT_LENGTH: 						12

};