#!/bin/bash

CWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
JSDOC2MD="${CWD}/../node_modules/jsdoc-to-markdown/bin/cli.js"

if [ -e "${CWD}/../API.md" ]; then
    rm "${CWD}/../API.md"
fi

node "$JSDOC2MD" --verbose "${CWD}/../source/**/*.js" > "${CWD}/../API.md"
